name: Send Email

on:
  workflow_dispatch:  # Ø§Ø¬Ø±Ø§ÛŒ Ø¯Ø³ØªÛŒ
  schedule:
    - cron: '*/8 * * * *'  # Ø§Ø¬Ø±Ø§ÛŒ Ø®ÙˆØ¯Ú©Ø§Ø± Ù‡Ø± 8 Ø¯Ù‚ÛŒÙ‚Ù‡

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "ğŸ“© Ù¾ÛŒØ§Ù… Ø§Ø®ØªØµØ§ØµÛŒ Ø§Ø² Ø¢Ú©Ø§Ø¯Ù…ÛŒ"
          html_body: |
            <div style="font-family:Tahoma; direction:rtl; text-align:right; background-color:#f9f9f9; padding:20px; border-radius:10px;">
              <img src="https://raw.githubusercontent.com/Academivpn73/DNS_panel/main/Academi_logo.png" alt="Academi Logo" width="180" style="margin-bottom:20px;" />
              <h3 style="color:#333;">ğ™Šğ™’ğ™‰ğ™€ğ™ â†´<br> <span style="color:#0077cc;">@Puriya73</span></h3>
              <p style="font-size:15px; line-height:1.6;">
                Ø¯Ø± Ø§ÛŒÙ† Ú©Ø§Ù†Ø§Ù„ Ù‡Ø¯Ù Ù…Ø§ Ø§ØªØµØ§Ù„ Ù¾Ø§ÛŒØ¯Ø§Ø± Ø´Ù…Ø§ Ø¨Ù‡ Ø§ÛŒÙ†ØªØ±Ù†Øª Ùˆ Ù¾Ø§Ø³Ø®Ú¯ÙˆÛŒÛŒ Ø¨Ù‡ Ù†ÛŒØ§Ø² Ù‡Ø§ÛŒ Ø´Ù…Ø§ Ø¯Ø± Ú©ÙˆØªØ§Ù‡â€ŒØªØ±ÛŒÙ† Ø²Ù…Ø§Ù† Ù…Ù…Ú©Ù† Ø¨Ø§ Ø§Ú©Ø§Ù†Øªâ€ŒÙ‡Ø§ÛŒ Ø§Ø®ØªØµØ§ØµÛŒ Ø§Ø³Øª.
              </p>
              <p style="font-size:15px;">
                <strong>ğ™‚ğ™ğ™Šğ™ğ™‹:</strong> <span style="color:#0077cc;">@Academi_team</span><br>
                <strong>ğ™ğ™ªğ™¥ğ™¥ğ™¤ğ™§ğ™©:</strong> <span style="color:#0077cc;">@Academii_support</span>
              </p>
              <p style="color:#e91e63; font-size:18px; font-weight:bold;">ğŸ’“ Ù‡Ù…Ø±Ø§Ù‡ÛŒ Ø´Ù…Ø§ Ø¨Ø§Ø¹Ø« Ø§ÙØªØ®Ø§Ø± Ù…Ø§Ø³Øª ğŸ’“</p>
            </div>
          to: academi.mah87@gmail.com
          from: Academi Vpn <c.a.s.t.on.g.va.ydi.di.a.ne@gmail.com>
